
#Entire container
services:

    my-travel-database-service:

            image: my-travel-database-image

            build: ./database

            container_name: my-travel-database-container

            ports:
                - 3306:3306
            
            environment:
                MARIADB_HOST: localhost
                MARIADB_DATABASE: mytravel
                MARIADB_ROOT_USER: michal
                MARIADB_ROOT_PASSWORD: vacations
            
            restart: unless-stopped

            volumes:
                - mytravel:/bitnami/mariadb

#---------------------------------------------------------

    my-travel-backend-service:

        image: my-travel-backend-image

        build: ./backend

        container_name: my-travel-backend-container

        ports:
            - 3001:3001
        
        environment:
            PORT: 4000
            MYSQL_HOST: my-travel-database-service
            NYSQL_USER: michal
            NYSQL_PASSWORD: vacations
        
        restart: unless-stopped

        volumes:
            - ./backend:/app
            - backend-files:/app/src/1-assets
        
        depends_on:
            - my-travel-database-service

#-------------------------------------------------------------

    my-travel-frontend-service:

        image: my-travel-frontend-image

        build: ./frontend

        container_name: my-travel-frontend-container

        ports:
            - 3000:3000

        restart: unless-stopped

        volumes:
            - ./frontend:/app
            - frontend-files:/app/src/1-Assets
        
        depends_on:
            - my-travel-backend-service


volumes:
    mytravel:
    backend-files:
    frontend-files: